[build]
builder = "DOCKERFILE"
dockerfilePath = "PMCRMS/backend/PMCRMS.API/Dockerfile"
dockerContext = "PMCRMS/backend/PMCRMS.API"

[deploy]
startCommand = "dotnet PMCRMS.API.dll"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
